<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>4b68d644-c254-477f-a3bc-ca9780c37360</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='img1']/div[2]/div/div/div/div/h4/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h4 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b27760b4-314f-4e86-8445-1eb8a9069de9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>a843f29a-3184-4c2f-8758-1dba9f746131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>02784d94-1c86-428a-8cfd-abca01b29460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tabmod</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>da6c78e9-eb3d-4bd4-bddd-231f1e01f83d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>디텍티브 나이트: 가면의 밤</value>
      <webElementGuid>578787f1-e928-4236-9a43-7e73ee34db41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-24&quot;)/div[@class=&quot;oj-listview-cell-element&quot;]/div[@id=&quot;img1&quot;]/div[@class=&quot;oj-lg-9 oj-md-9 oj-sm-8 oj-flex-item&quot;]/div[@class=&quot;oj-flex&quot;]/div[@class=&quot;oj-lg-9 oj-md-9 oj-sm-12 oj-flex-item&quot;]/div[1]/div[1]/h4[1]/a[1]</value>
      <webElementGuid>6636b7cd-c2c1-453a-bfa9-89a08835cfcb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='img1']/div[2]/div/div/div/div/h4/a</value>
      <webElementGuid>5d866f85-c3b2-446c-a283-3b548c8e7f93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'디텍티브 나이트: 가면의 밤')]</value>
      <webElementGuid>fa7b0c25-bbcd-4ec0-92f9-aa15b5bf7213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Release Date :'])[1]/following::a[1]</value>
      <webElementGuid>24cf065a-f775-4bad-ad61-140d57f407ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Votes Average :'])[1]/following::a[1]</value>
      <webElementGuid>53a4bcf1-e062-4afe-b681-7e8a1b9f7990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='디텍티브 나이트: 가면의 밤']/parent::*</value>
      <webElementGuid>ee2c4886-85e8-462d-bfff-a2874b7d8f7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[18]</value>
      <webElementGuid>44d95e4c-1680-48f2-9355-3c0c67dbe719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4/a</value>
      <webElementGuid>148ada25-18ec-49e9-96b8-5411a37bdb2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '디텍티브 나이트: 가면의 밤' or . = '디텍티브 나이트: 가면의 밤')]</value>
      <webElementGuid>d8dc4526-8a60-4f27-be8c-aa7eb3069d70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
