<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Title_imgOne</name>
   <tag></tag>
   <elementGuidId>6d79eb3c-3cbd-4257-b4b1-c88757a34191</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='imgOne']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#imgOne</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>22cee584-df3f-4641-9208-f2147cc3d8b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>imgOne</value>
      <webElementGuid>262801b0-5f6d-4c87-80ca-c208e53b6b47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr: {'src': selPosterPath}</value>
      <webElementGuid>d3eac9cb-9707-44f2-a796-b5b00e59024e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://image.tmdb.org/t/p/w185//7TxWlHkz5Guc9DCYo7ruVvnskDk.jpg</value>
      <webElementGuid>39cc1d08-1fda-48a8-97f5-bf901527cf6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;imgOne&quot;)</value>
      <webElementGuid>0d0792e6-648e-4d64-a9c9-6e6b04cb370c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='imgOne']</value>
      <webElementGuid>cb676d00-8df7-4ceb-ac59-5a4150ec29c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//oj-popup[@id='popup1']/div/div/img</value>
      <webElementGuid>a9b37618-1b28-4d5a-a6e7-6dbf42010680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://image.tmdb.org/t/p/w185//7TxWlHkz5Guc9DCYo7ruVvnskDk.jpg')]</value>
      <webElementGuid>243df194-41c7-45c9-bde5-eabac59508e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>5dfec468-23e8-4677-b512-d2a7b518b4d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'imgOne' and @src = 'https://image.tmdb.org/t/p/w185//7TxWlHkz5Guc9DCYo7ruVvnskDk.jpg']</value>
      <webElementGuid>9d279f7b-79db-4cde-9214-815ad050485b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
