<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>68b54bf2-9422-435b-aeb0-c077cb5afc37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='amybartlet']/div/div/div/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f76ea0ce-ecba-4931-bff5-eaa900682321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>5e6fcd39-cb45-40a2-b942-f4fa813fad96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>디텍티브 나이트: 가면의 밤</value>
      <webElementGuid>d6512c2c-ed6c-41ca-ac30-a566c200247c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-22&quot;)/li[@id=&quot;amybartlet&quot;]/div[@class=&quot;oj-listview-cell-element&quot;]/div[@class=&quot;container&quot;]/div[1]/span[@class=&quot;name&quot;]</value>
      <webElementGuid>4c11c224-be70-43b5-abbb-f8f416a0d845</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='amybartlet']/div/div/div/span[2]</value>
      <webElementGuid>6cdbfe4e-e6aa-4877-bc62-42fb070376e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title :'])[1]/following::span[1]</value>
      <webElementGuid>5123ba8a-7cf5-4c0c-9f89-e47ad81bdd30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='People :'])[1]/preceding::span[2]</value>
      <webElementGuid>7afc151c-b60c-413e-a0fc-e5575246de98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='브루스 윌리스,에드워드 드레이크,지미 장-루이스,로슬린 먼로'])[1]/preceding::span[3]</value>
      <webElementGuid>ad278c06-269c-4ca6-8216-637ef01ba7f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='디텍티브 나이트: 가면의 밤']/parent::*</value>
      <webElementGuid>9c48e248-4427-4382-806a-51e0c44afe46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>91033de0-1996-40ea-b61f-aadb61163507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '디텍티브 나이트: 가면의 밤' or . = '디텍티브 나이트: 가면의 밤')]</value>
      <webElementGuid>778f64f8-7ae3-4390-bbff-5a5876144a4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
