<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_View Detail</name>
   <tag></tag>
   <elementGuidId>b3a4bf90-d641-4119-a3e5-5a7a970474ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ui-id-27']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-27</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0b9e1ef2-be44-433e-a91b-ce152ac6591e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oj-button-text</value>
      <webElementGuid>4b08aae3-76f4-4924-a335-f1dcb95c39f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-27</value>
      <webElementGuid>9341f11d-7a72-4095-aac8-6ae636c8a5ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Detail
                                            </value>
      <webElementGuid>27d01b07-bf81-4007-8657-53f9f48310d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-27&quot;)</value>
      <webElementGuid>3ec55791-c1b9-4dc9-b760-596e483776c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ui-id-27']</value>
      <webElementGuid>621c3de6-d716-4075-84a4-30a882de187b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//oj-button[@id='1024546']/button/div/span</value>
      <webElementGuid>02417b5a-375d-4ad5-884c-6ba78450386a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View Detail']/parent::*</value>
      <webElementGuid>700e8303-6d49-4781-ab1a-02875b64e743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/oj-button/button/div/span</value>
      <webElementGuid>92ef80df-53e7-4068-849c-f7af3389ccbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ui-id-27' and (text() = 'View Detail
                                            ' or . = 'View Detail
                                            ')]</value>
      <webElementGuid>98c1c0c2-58de-463b-8482-c8ba21c47307</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
