<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_View Detail</name>
   <tag></tag>
   <elementGuidId>4063a5ed-bea5-42de-b761-91e152d98bb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ui-id-27']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-27</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7a8d9d34-a099-41dd-9539-7b491d2c6fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oj-button-text</value>
      <webElementGuid>01812dc7-a847-4eb7-b00e-5656454f9d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-27</value>
      <webElementGuid>f88f19cf-e735-4957-bba0-cc4aa6620bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Detail
                                            </value>
      <webElementGuid>a0604f24-5c38-44f3-9991-38864dac8e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-27&quot;)</value>
      <webElementGuid>2a7e82bc-4079-46d7-bd4e-7acd1fc31ef6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ui-id-27']</value>
      <webElementGuid>e1dbd21c-d541-43f3-96ee-dcb1932420d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//oj-button[@id='1024546']/button/div/span</value>
      <webElementGuid>46e7fd8e-ea29-4e47-ba68-35204f1f48a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View Detail']/parent::*</value>
      <webElementGuid>1b011567-be97-4f19-b3d6-bca98c38ef68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/oj-button/button/div/span</value>
      <webElementGuid>c2ddb351-7ca6-4e14-a5ac-10f6a616fc5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ui-id-27' and (text() = 'View Detail
                                            ' or . = 'View Detail
                                            ')]</value>
      <webElementGuid>66fd6d50-7d58-493e-b542-368a28425633</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
